# Generated by Django 2.0 on 2017-12-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('artist_name', models.CharField(max_length=225)),
                ('duration', models.IntegerField()),
                ('artwork', models.ImageField(upload_to='images')),
            ],
        ),
    ]
